### ISSUE TITLE
Usage instructions in README

### ISSUE THREAD

**Issue by hoijui** [ajuvercr/jsonld-lsp#5]
Woah cool! :-)
glad to see this, and even in Rust!
thank you!

I am mostly interested in the turtle support, but.. think I did not yet get it working well.
I would like to see instructions for that in the README too, and next to NVim, also for [Helix](https://helix-editor.com/) - A quite well received Vim/Kakoune alternative written in Rust.

This is what I did to configure Helix, and .. I think it .. works, but am not sure:

`~/.config/helix/languages.toml`:

```toml
[language-server.turtle-lsp]
command = "turtle-language-server"

[[language]]
name = "turtle"
scope = "source.ttl"
injection-regex = "turtle"
file-types = ["ttl"]
comment-token = "#"
indent = { tab-width = 2, unit = "  " }
#formatter = { command = "mylang-formatter" , args = ["--stdin"] }
language-servers = [ "turtle-lsp" ]
```
